package TeleDoc;
interface MedicineDirectory{
    String[] kidneyInfectionMeds();
    String[] kidneyStonesMeds();
    String[] kidneyCancerMeds();
    String[] lupusMeds();
    String[] acneMeds();
    String[] eczemaMeds();
    String[] lowBackPainMeds();
    String[] fracturesMeds();
    String[] osteoarthritisMeds();
    String[] achalasiaMeds();
    String[] stomachCancerMeds();
    String[] gastroparesisMeds();
    String[] glaucomaMeds();
    String[] cataractsMeds();
    String[] strabismusMeds();
    String[] gingivitisMeds();
    String[] oralCancerMeds();
    String[] cavitiesMeds();
    String[] earInfectionsMeds();
    String[] noiseMeds();
    String[] tinnitusMeds();
    String[] sinusitisMeds();
    String[] nasalCancerMeds();
    String[] noseInjuriesMeds();
    String[] tonsillitisMeds();
    String[] voiceDisorderMeds();
    String[] dysphagiaMeds();
    String[] anemiaMeds();
    String[] typhoidMeds();
    String[] diarrhoeaMeds();
}

